{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "release.name" . }}
  labels:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "chart.name_version" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClass.enabled }}
  ingressClassName: {{.Values.ingress.ingressClass.name}}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "release.name" . }}
                port:
                  number: {{ .Values.service.port }}
            pathType: {{ .Values.ingress.pathType }}
              {{- else }}
              serviceName: {{ template "release.name" . }}
              servicePort: {{ .Values.service.port }}
    {{- end }}
  {{- end }}
{{- end }}
